#!/usr/bin/python
# This is a FORTH to C compiler, handling only a subset of FORTH.
# Modified from <http://yosefk.com/blog/c-as-an-intermediate-language.html>
halp="""\
forth2c: a Forth to C compiler for a (very) limited subset of Forth.

For how the system works, consult the article:

http://yosefk.com/blog/c-as-an-intermediate-language.html

This transpiler requires understanding the Forth runtime environment
provided in the 'forth_runtime.h' header.

Options:

    -h          Print this help message and exit.
    -o  FILE    Change the output file from the default.
    -l          Turn line numbers on in generated C output.
    -e  NAME    Set the name of the entry point
    -s  SIZE    Set the size of the stack/memory
    -m          Turn on defining 'main()' in generated C code

Returns non-zero on failure.
"""

import sys, getopt

special = { # "special" words - can't emit S=WORD(S)
  ':':'',
  ';':'return CHK(F,S); }',
  'exit':'return CHK(F,S);',
  'cell':'S = PUSH(F,S,sizeof(DATA));',
  'begin':'do {',
  'again':'} while(1);',
  'until':'} while(!*S++);',
  'repeat':'} while(1);',
  'while':'if(!*S++) break;',
  'if':'if(*S++) {',
  'else':'} else {',
  'then':'}',
  'for':'for(*(++F->R) = *S++; *F->R > 0; (*F->R)--){',
  'next':'} F->R--;',
}

unops='not invert 1+ 1- 2+ 2-'.split()
binops='+ - * / = < > mod and or xor lshift rshift'.split()
op2c={'=':'==','mod':'%','and':'&','or':'|','xor':'^','lshift':'<<','rshift':'>>','not':'-!','1-':'-1 +','2-':'-2 +','invert':'~'}

def mangle(s):
  m={'.':'PRINT',',':'COMMA','!':'STORE','@':'LOAD','#':'HASH','+':'PLUS','-':'MINUS','0':'ZERO','1':'ONE','2':'TWO'}
  r=""
  for c in s:
    if c in m:
      r += m[c]
    else:
      r += c
  return r

var={'h0':0,'size':1,'rp':2} # 'h0' must be first declared variable
nvars = len(var)

def forth2c(inf,out,lndir,entry):
  global nvars
  defining=0
  variable=0
  last = ""
  n = 0
  for line in inf:
    n += 1
    if lndir: # emit line info for C tools (debuggers, etc.) - a nice option C gives us
      print('\n#line',n,'"%s"'%infile, file=out)
    for token in line.lower().strip().split():
      mangled = mangle(token)
      if token == '\\':
          break
      elif token == 'recurse':
        print('S=%s(F, S);'%mangle(last), file=out)
      elif token in special:
        print(special[token], file=out)
      else:
        try:
          num = int(token)
          print('S = PUSH(F,S,%dll);'%num, file=out)
        except ValueError:
          if token in unops:
            print('S = OP1(F,S,%s);'%op2c.get(token,token), file=out)
          elif token in binops:
            print('S = OP2(F,S,%s);'%op2c.get(token,token), file=out)
          else:
            if defining:
              static = 'static'
              if token == entry:
                static = ' '
              print('%s DATA* '%static+mangled+'(FORTH *F, DATA *S) { CHK(F,S);',file=out)
              last = token
            elif variable:
              var[token] = nvars
              nvars += 1
            else: # call
              if token in var:
                print('S = PUSH(F,S,(DATA)&(F->stack[%d]'%var[token]+'/* %s */));'%token,file=out)
              elif token != 'variable':
                print('S=%s(F,S);'%mangled,file=out)
      defining = token == ':'
      variable = token == 'variable'

outfile='forth_program.c'
entry='cold'
lndir=0
defmain=0
size=4096
optlist, args = getopt.getopt(sys.argv[1:], "ho:le:s:m")

for o, a in optlist:
  if o == '-h':
    print(halp)
    sys.exit()
  elif o == '-o':
    outfile = a
  elif o == '-l':
    lndir = 1
  elif o == '-e':
    entry = a
  elif o == '-m':
    defmain = 1
  elif o == '-s':
    size = a
  else:
    assert False, "invalid option"

out = open(outfile,'w')
print('#define FORTH_ENTRY_POINT %s'%entry,file=out)
print('#define FORTH_SIZE (%d)'%size,file=out)
print('#include "forth_runtime.h"\n',file=out)
for infile in args:
  forth2c(open(infile),out,lndir,entry)
print("int main(void) { ",file=out)
print("  static DATA stack[FORTH_SIZE];",file=out)
print("  FORTH F;",file=out)
print("  FORTH_INIT(&F, %d, stack, FORTH_SIZE);"%nvars,file=out)
print("  return *(%s(&F, F.stack+FORTH_SIZE));"%entry,file=out)
print("}",file=out)
